name: grabbing streams

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U yt-dlp requests

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Update Bot"

      - name: Grab m3u files
        working-directory: ./core/platforms
        continue-on-error: true
        run: |
          # Twitch Streams      
          python3 twitch.py 34100tv > ../../streams/34100tv.m3u8
          python3 twitch.py altertvcy > ../../streams/ALTER_CY.m3u8
          python3 twitch.py aktinaradio > ../../streams/AKTINA_RADIO.m3u8
          python3 twitch.py alithiavideo > ../../streams/ALITHIA_TV.m3u8
          python3 twitch.py radiotvanemosgr > ../../streams/ANEMOS_RADIO.m3u8
          python3 twitch.py astratv2021 > ../../streams/ASTRA_TV.m3u8
          python3 twitch.py astratv2019 > ../../streams/ASTRA_TV_2.m3u8
          python3 twitch.py chanialivetv > ../../streams/CHANIA_TV.m3u8
          python3 twitch.py diavata_tv > ../../streams/DIABATA_TV.m3u8
          python3 twitch.py dtptvnet > ../../streams/DTP.m3u8
          python3 twitch.py ellada943fm > ../../streams/ELLADA_TV.m3U8
          python3 twitch.py failarmy > ../../streams/FAILARMY.m3u8
          python3 twitch.py farostv1959 > ../../streams/FAROS_TV_EKKLISIA.m3u8
          python3 twitch.py fatsabooktv > ../../streams/FATSABOOK_TV.m3u8
          python3 twitch.py younowflashtv > ../../streams/FLASH_TV.m3u8
          python3 twitch.py freeangelwebtv > ../../streams/FREE_ANGEL.m3u8
          python3 twitch.py hotbeatstv > ../../streams/HOTBEAST_TV.m3u8
          python3 twitch.py iviewtvgr > ../../streams/IVIEW_TV.m3u8
          python3 twitch.py konitsaplustv > ../../streams/KONITSA_TV.m3u8
          python3 twitch.py radiomakedonia > ../../streams/MAKEDONIA_RADIO.m3u8
          python3 twitch.py oloutheradio > ../../streams/OLOUTHE_RADIO.m3u8
          python3 twitch.py ontv2023 > ../../streams/ON_TV.m3u8
          python3 twitch.py orthodoxiaradio > ../../streams/ORTHODOXIA_TV.m3u8
          python3 twitch.py pakoestream > ../../streams/PAKOE_TV.m3u8
          python3 twitch.py zefstv1 > ../../streams/PLUTON_TV.m3u8
          python3 twitch.py midnightsumo > ../../streams/SUMO.m3u8
          python3 twitch.py xtvision > ../../streams/XTVISION.m3u8
          python3 twitch.py xtvision2 > ../../streams/XTVISION_2.m3u8 
          
          # Dailymotion Streams
          python3 dailymotion.py xar7s56 > ../../streams/EURONEWS.m3u8


      - name: Commit & Push changes
        run: |
          git add -A
          git commit -m "streams updated" || echo "No changes"
          git push



